spring:
  datasource:
    #    url: jdbc:mysql://localhost:3306/elbuensabor?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    url: jdbc:mysql://containers-us-west-34.railway.app:6720/railway
    username: root
    #    password: root
    password: NlroDIgs4MPhP3XZmxOc
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  servlet:
    multipart:
      max-file-size: 5MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: lacodigoneta@gmail.com
    password: qunztbndxzfikjvv
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          writetimeout: 5000
          connectiontimeout: 5000
          ssl:
            trust: "*"
          starttls:
            enable: true
            required: true
web:
  origin: https://el-buen-sabor-frontend-production.up.railway.app

upload:
  dir: ./uploads/images/

security:
  key: ElBuenSaborProyectoProgramacion1

google:
  client-id: 884827796185-0a0kvmu2gj381vvnfmh7ekd8j3a2o613.apps.googleusercontent.com

mercado-pago:
  token: TEST-2872458347585384-061000-5b7c71de414edf7b8bf9faf689f4e197-331144077

server:
  port: ${PORT}